@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account

POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "joao menna",
    "email": "joaomenna1@gmail.com",
    "password": "12345"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "joaomenna1@gmail.com",
    "password": "12345"
}

###

# @name create_url

POST {{baseUrl}}/create-url
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "url": "https://www.loja21.com/"
}

###

#   @name fetch_recent_urls

GET  {{baseUrl}}/urls?page=1
Authorization: Bearer {{authToken}}

###

#   @name get_one_user

GET  {{baseUrl}}/profile/me
Authorization: Bearer {{authToken}}
###

#   @name delete_url

DELETE   {{baseUrl}}/delete-url?id=d3ef1120-c09d-4e24-b173-3039958463e1
Authorization: Bearer {{authToken}}
###

# @name URL_MONITORING

POST {{baseUrl}}/monitor
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "url": "https://pie.dev/get"
}

###